### ISSUE TITLE
Devel branch crashes after some time on every command

### ISSUE THREAD

**Issue by Natenom** [dafoxia/mumble-ruby-pluginbot#143]
The error is always the same:

Debug: Got a message from "username bla" (user id: 1234, session id: 55). Content: ".ch"
Error: An error occurred: undefined method `[]' for nil:NilClass
Error: Backtrace: ["/home/botmaster/src/mumble-ruby-pluginbot/plugins/messages.rb:41:in `handle_chat'", "/home/botmaster/src/mumble-ruby-pluginbot/core/pluginbot.rb:335:in `block in handle_text_message'", "/home/botmaster/src/mumble-ruby-pluginbot/core/pluginbot.rb:334:in `each'", "/home/botmaster/src/mumble-ruby-p
luginbot/core/pluginbot.rb:334:in `handle_text_message'", "/home/botmaster/src/mumble-ruby-pluginbot/core/pluginbot.rb:215:in `block in mumble_start'", "/home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/client.rb:258:in `call'", "/home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-r
uby-1.1.2/lib/mumble-ruby/client.rb:258:in `block in run_callbacks'", "/home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/client.rb:258:in `each'", "/home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/client.rb:258:in `run_callbacks'", "/home/botmaster/.rvm
/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/client.rb:249:in `read'", "/home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2/

**Comment by Natenom** [comment]
@dafoxia: Before you made this patch I added a return after the line "super" in handle_chat of messages.rb to disable it; the bots are running now for a test...

**Comment by Natenom** [comment]
It seems that the "return" change fixed it; no bot crash so far.
